### ISSUE TITLE
Active Directory problem

### ISSUE THREAD

**Issue by truefriend-cz** [NethServer/arm-dev#42] opened 2020-11-06 21:29 UTC
On R Pi 4 B do not install Active Directory
After install many hours waiting if show info text "Installing nethserver-dc-1.8.1-1.ns7.armv7hl" message.

Steps:
1. clean flash
2. change IP to static
3. reboot device
4. Install Active Directory from "Users and Groups"

Tested on version: 7.8.2003 Final, 7.8.2003 RC2, 7.8.2003 RC1
Version 7.7.1908 RC1 worked ok

**Comment by markVnl** [comment] 2020-12-13 16:01
Sorry for the late reply ;(

Just did an install on NS 7.8.2003 and 7.9.2009 without an issue,
with tho only difference being setting a hostname to the steps you described. 

in other words: I'm a bit puzzeld...

**Comment by markVnl** [comment] 2020-12-24 09:01
Have done several new installs and cannot reproduce.. 

closing this, feel free to reopen if it does not work for you (@truefriend-cz)

**Closed as completed by markVnl** 2020-12-24 09:01 UTC
Labels: wontfix
